server:
  port: 9091

spring:
  application:
    name: Product Microservice
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
  profiles:
    active: local
  boot:
    admin:
      client:
        url:
          - http://${ADMIN_HOST}:${ADMIN_PORT}

logging:
  file:
    name: d:\logs\product.log
#    path: d:\logs  #spring.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
  level:
    root: INFO

# actuator specific

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS
  health:
    mongo:
      enabled: true

info:
  app:
    name: Product Microservice
    version: 1.0
    desccription: Add and retrieve product information

product:
  currencies:
    - INR
    - USD
    - EUR

---
spring:
  config:
    activate:
      on-profile:
        - local
  application:
    name: Product Microservice(Local Env)


