apiVersion: v1
kind: Service
metadata:
  name: product-svc
  labels:
    app: userservice
spec:
  ports:
    - nodePort: 30155 
      port: 9091  
      targetPort: 9091  
      protocol: TCP
  selector:           
    app: productservice
  type: NodePort   


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: productservice
spec:
  selector:
    matchLabels:
      app: productservice
  template:
    metadata:
      labels:
        app: productservice
    spec:
      containers:
        - name: productservice
          image: productservice
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 9091
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mongo_host

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mongo_port

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mongo_db_name

            - name: ADMIN_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key:  admin_host
                  
            - name: ADMIN_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key:  admin_port  
          resources: {}