apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
data:  
  mysql-root-password: cGFzc3dvcmQ=
  mysql-user: YWRtaW4=  
  mysql-password: cGFzc3dvcmQ=
  mail_username: ZWZmZTQ1YTM3NTdhOTg=
  mail_password: NDM4OGU3ODc2Y2JjMjI=

