apiVersion: v1
kind: Service
metadata:
  name: usersvc
  labels:
    app: userservice
spec:
  ports:
    - nodePort: 30153 
      port: 8082      
      targetPort: 8081  
      protocol: TCP
  selector:           
    app: userservice
  type: NodePort   


---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
spec:
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: userservice
          imagePullPolicy: IfNotPresent          
          ports:
            - containerPort: 8081
          env:
            - name: APP_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: port
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-user

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password

            - name: DB_PORT
              value: '3306'

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key:  db_host
                  
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key:  mysql
          resources: {}